on:
  push:
    branches:
      - docker

name: Deploy to AWS ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      REGION: us-east-1
      CLUSTER_NAME: staging
      SERVICE_NAME: omnia-staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: latest
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t ${ECR_REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG} .
        docker push ${ECR_REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}
        echo "::set-output name=image::${ECR_REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}"
